import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { CAR_MODELS } from '../data/modelsData';
import { ModelCard3D } from '../components/ModelCard3D';

interface MetricSpec {
  label: string;
  w14: number | string;
  w11: number | string;
  one: number | string;
  unit: string;
  description: string;
  higherIsBetter: boolean;
}

const COMPARISON_METRICS: MetricSpec[] = [
  {
    label: 'Top Speed',
    w14: 352,
    w11: 360,
    one: 352,
    unit: 'km/h',
    description: 'Measured with DRS opened in low-drag configuration at Autodromo Nazionale Monza.',
    higherIsBetter: true,
  },
  {
    label: '0 - 100 km/h Acceleration',
    w14: 2.6,
    w11: 2.4,
    one: 2.9,
    unit: 'sec',
    description: 'Standing start with race compound slick tires on prepped asphalt.',
    higherIsBetter: false,
  },
  {
    label: 'Combined System Output',
    w14: 1025,
    w11: 1040,
    one: 1063,
    unit: 'HP',
    description: '1.6L V6 Turbo ICE coupled with high-voltage MGU-K and MGU-H hybrid deployment.',
    higherIsBetter: true,
  },
  {
    label: 'Aerodynamic Downforce @ 250 km/h',
    w14: 1450,
    w11: 1650,
    one: 700,
    unit: 'kg',
    description: 'Peak vertical aerodynamic load generated by front wing, Venturi floor, and rear wing.',
    higherIsBetter: true,
  },
  {
    label: 'Peak Lateral G-Force',
    w14: 5.2,
    w11: 5.6,
    one: 2.8,
    unit: 'G',
    description: 'Maximum sustained lateral grip recorded through Copse and Pouhon.',
    higherIsBetter: true,
  },
  {
    label: 'Power-to-Weight Ratio',
    w14: 1.28,
    w11: 1.39,
    one: 0.63,
    unit: 'HP/kg',
    description: 'Horsepower per kilogram including driver and minimum regulation ballast.',
    higherIsBetter: true,
  },
  {
    label: '200 - 0 km/h Braking Distance',
    w14: 54,
    w11: 51,
    one: 84,
    unit: 'meters',
    description: 'Carbon-carbon discs with regenerative brake-by-wire MGU-K energy harvesting.',
    higherIsBetter: false,
  },
];

export const PerformancePage: React.FC = () => {
  const [selectedCarId, setSelectedCarId] = useState<string>('w14');
  const [rpmValue, setRpmValue] = useState<number>(11500);
  const [isSimulatingRace, setIsSimulatingRace] = useState<boolean>(false);
  const [raceProgress, setRaceProgress] = useState<{ [key: string]: number }>({ w14: 0, w11: 0, one: 0 });

  const activeCar = CAR_MODELS.find((c) => c.id === selectedCarId) || CAR_MODELS[0];

  // Dyno calculations based on RPM
  const iceHorsepower = Math.round((rpmValue / 15000) * 860);
  const mgukHorsepower = rpmValue > 4000 ? 163 : Math.round((rpmValue / 4000) * 163);
  const totalPower = iceHorsepower + mgukHorsepower;
  const turboBoostBar = (1.8 + (rpmValue / 15000) * 2.2).toFixed(2);
  const fuelFlowKgH = Math.min(100, Math.round((rpmValue / 10500) * 100));

  const startRaceSimulation = () => {
    if (isSimulatingRace) return;
    setIsSimulatingRace(true);
    setRaceProgress({ w14: 0, w11: 0, one: 0 });

    const startTime = Date.now();
    const duration = 4000;

    const interval = setInterval(() => {
      const elapsed = Date.now() - startTime;
      const progress = Math.min(1, elapsed / duration);

      // W11 finishes first (0-300 km/h), then W14, then AMG ONE
      setRaceProgress({
        w11: Math.min(100, progress * 100 * 1.05),
        w14: Math.min(100, progress * 100 * 0.98),
        one: Math.min(100, progress * 100 * 0.88),
      });

      if (progress >= 1) {
        clearInterval(interval);
        setTimeout(() => setIsSimulatingRace(false), 800);
      }
    }, 30);
  };

  return (
    <div className="min-h-screen pt-28 pb-20 px-6 md:px-12 max-w-7xl mx-auto">
      {/* Header Banner */}
      <div className="text-center max-w-3xl mx-auto mb-14">
        <motion.div
          initial={{ opacity: 0, y: -8 }}
          animate={{ opacity: 1, y: 0 }}
          className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-[rgba(17,23,25,0.06)] border border-[rgba(17,23,25,0.10)] mb-3"
        >
          <span className="w-1.5 h-1.5 rounded-full bg-accent-teal animate-pulse" />
          <span className="text-[10px] font-mono font-bold tracking-[0.22em] text-accent-teal uppercase">
            MERCEDES-AMG TELEMETRY & DYNAMICS BENCHMARK
          </span>
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="font-condensed font-black text-4xl sm:text-6xl md:text-7xl uppercase text-[#151A1C] tracking-tight leading-[0.95]"
        >
          PERFORMANCE{' '}
          <span className="bg-gradient-to-r from-accent-teal via-[#2BE7D6] to-accent-teal bg-clip-text text-transparent">
            ARENA
          </span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.2 }}
          className="text-xs sm:text-sm text-[#5E686B] mt-4 max-w-xl mx-auto leading-relaxed font-normal"
        >
          Compare raw dyno outputs, aerodynamic downforce loads, and track telemetry across Formula 1 champions and road-legal hypercar engineering.
        </motion.p>
      </div>

      {/* Model Switcher Tabs */}
      <div className="flex flex-wrap items-center justify-center gap-3 mb-12">
        {CAR_MODELS.map((car) => {
          const isSelected = car.id === selectedCarId;
          return (
            <button
              key={car.id}
              onClick={() => setSelectedCarId(car.id)}
              className={`px-5 py-2.5 rounded-xl font-mono text-xs font-bold tracking-wider transition-all duration-300 uppercase cursor-pointer flex items-center space-x-3 border ${
                isSelected
                  ? 'bg-[#151A1C] text-white border-[#151A1C] shadow-lg shadow-black/10'
                  : 'bg-white/80 hover:bg-white text-[#5E686B] border-[rgba(17,23,25,0.12)] hover:border-accent-teal/60'
              }`}
            >
              <span className={`w-2 h-2 rounded-full ${isSelected ? 'bg-accent-teal animate-pulse' : 'bg-gray-300'}`} />
              <span>{car.name}</span>
              <span className="text-[10px] opacity-60">({car.year})</span>
            </button>
          );
        })}
      </div>

      {/* Top Section: Active 3D Machine Card & Quick Telemetry Gauges */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 mb-16 items-center">
        {/* Left: 3D Interactive Viewport */}
        <div className="lg:col-span-7 glass-panel rounded-2xl p-6 border border-[rgba(17,23,25,0.12)] shadow-sm relative overflow-hidden">
          <div className="flex items-center justify-between mb-3">
            <div>
              <span className="text-[10px] font-mono font-bold tracking-widest text-accent-teal uppercase">
                {activeCar.category} // {activeCar.year}
              </span>
              <h2 className="font-condensed font-black text-2xl sm:text-3xl text-[#151A1C] uppercase">
                {activeCar.name}
              </h2>
            </div>
            <Link
              to={`/models/${activeCar.id}`}
              className="px-4 py-1.5 rounded-lg bg-accent-teal hover:bg-accent-teal/90 text-white font-mono text-xs font-bold tracking-widest uppercase transition-all duration-200 flex items-center space-x-1"
            >
              <span>INSPECT 3D</span>
              <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                <polyline points="9 18 15 12 9 6" />
              </svg>
            </Link>
          </div>

          {/* 3D Model Render Canvas */}
          <div className="h-[280px] sm:h-[340px] w-full rounded-xl overflow-hidden bg-gradient-to-b from-white to-[#EEF2F0] border border-[rgba(17,23,25,0.06)] relative">
            <ModelCard3D
              modelPath={activeCar.modelPath}
              scale={activeCar.scale}
              rotationOffset={activeCar.rotationOffset}
            />
            <div className="absolute bottom-3 left-3 bg-white/80 backdrop-blur-md px-3 py-1 rounded-md border border-[rgba(17,23,25,0.10)] text-[10px] font-mono text-[#5E686B]">
              CLICK & DRAG TO ORBIT 360°
            </div>
          </div>
        </div>

        {/* Right: Key Performance Telemetry Metrics */}
        <div className="lg:col-span-5 flex flex-col space-y-4">
          <div className="glass-panel rounded-2xl p-6 border border-[rgba(17,23,25,0.12)]">
            <div className="flex items-center justify-between mb-4">
              <span className="text-xs font-mono font-bold tracking-widest text-[#5E686B] uppercase">
                POWERTRAIN OUTPUT
              </span>
              <span className="px-2 py-0.5 rounded bg-accent-teal/10 text-accent-teal font-mono text-[10px] font-bold">
                FUEL FLOW: {fuelFlowKgH} KG/H
              </span>
            </div>
            <div className="flex items-baseline space-x-2 mb-2">
              <span className="font-condensed font-black text-5xl sm:text-6xl text-[#151A1C]">
                {activeCar.engine.horsepower}
              </span>
            </div>
            <p className="text-xs text-[#5E686B] leading-relaxed">
              {activeCar.engine.name} with PU106 hybrid motor-generator units ({activeCar.engine.mguK} & high-speed {activeCar.engine.mguH}).
            </p>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="glass-panel rounded-2xl p-5 border border-[rgba(17,23,25,0.12)]">
              <span className="text-[10px] font-mono font-bold tracking-widest text-[#5E686B] uppercase block mb-1">
                TOP SPEED
              </span>
              <span className="font-condensed font-black text-3xl sm:text-4xl text-[#151A1C]">
                {activeCar.performance.topSpeed}
              </span>
            </div>
            <div className="glass-panel rounded-2xl p-5 border border-[rgba(17,23,25,0.12)]">
              <span className="text-[10px] font-mono font-bold tracking-widest text-[#5E686B] uppercase block mb-1">
                0-100 KM/H
              </span>
              <span className="font-condensed font-black text-3xl sm:text-4xl text-accent-teal">
                {activeCar.performance.acceleration}
              </span>
            </div>
            <div className="glass-panel rounded-2xl p-5 border border-[rgba(17,23,25,0.12)]">
              <span className="text-[10px] font-mono font-bold tracking-widest text-[#5E686B] uppercase block mb-1">
                MINIMUM WEIGHT
              </span>
              <span className="font-condensed font-black text-3xl sm:text-4xl text-[#151A1C]">
                {activeCar.performance.weight}
              </span>
            </div>
            <div className="glass-panel rounded-2xl p-5 border border-[rgba(17,23,25,0.12)]">
              <span className="text-[10px] font-mono font-bold tracking-widest text-[#5E686B] uppercase block mb-1">
                AERO DOWNFORCE
              </span>
              <span className="font-condensed font-black text-3xl sm:text-4xl text-[#151A1C]">
                {activeCar.performance.downforce}
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Interactive Dyno Engine Simulation */}
      <div className="glass-panel rounded-2xl p-6 sm:p-8 border border-[rgba(17,23,25,0.12)] mb-16 shadow-sm">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 border-b border-[rgba(17,23,25,0.08)] pb-4">
          <div>
            <span className="text-[10px] font-mono font-bold tracking-widest text-accent-teal uppercase block">
              VIRTUAL DYNAMOMETER
            </span>
            <h3 className="font-condensed font-black text-2xl sm:text-3xl text-[#151A1C] uppercase">
              LIVE ENGINE RPM & TURBO BOOST HARVESTING
            </h3>
          </div>
          <div className="flex items-center space-x-3">
            <span className="font-mono text-xs text-[#5E686B]">CURRENT TACHOMETER:</span>
            <span className="px-3 py-1 rounded bg-[#151A1C] text-accent-teal font-mono font-bold text-sm">
              {rpmValue.toLocaleString()} RPM
            </span>
          </div>
        </div>

        {/* RPM Scrubber Slider */}
        <div className="mb-8">
          <input
            type="range"
            min="2500"
            max="15000"
            step="100"
            value={rpmValue}
            onChange={(e) => setRpmValue(Number(e.target.value))}
            className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-accent-teal"
          />
          <div className="flex justify-between text-[10px] font-mono text-[#5E686B] mt-2">
            <span>2,500 IDLE</span>
            <span>7,500 MID-RANGE</span>
            <span>10,500 MAX FUEL FLOW (100 kg/h)</span>
            <span className="text-red-500 font-bold">15,000 FIA REDLINE</span>
          </div>
        </div>

        {/* Live Calculated Dyno Readouts */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="p-4 rounded-xl bg-white border border-[rgba(17,23,25,0.08)] shadow-sm">
            <span className="text-[10px] font-mono font-bold text-[#5E686B] uppercase block mb-1">
              ICE HORSEPOWER
            </span>
            <span className="font-condensed font-black text-3xl text-[#151A1C]">{iceHorsepower}</span>
            <span className="text-xs font-mono text-[#5E686B] ml-1">BHP</span>
            <div className="w-full bg-gray-100 h-1.5 rounded-full mt-2 overflow-hidden">
              <div
                className="bg-[#151A1C] h-full transition-all duration-150"
                style={{ width: `${(iceHorsepower / 860) * 100}%` }}
              />
            </div>
          </div>

          <div className="p-4 rounded-xl bg-white border border-[rgba(17,23,25,0.08)] shadow-sm">
            <span className="text-[10px] font-mono font-bold text-[#5E686B] uppercase block mb-1">
              MGU-K HYBRID BOOST
            </span>
            <span className="font-condensed font-black text-3xl text-accent-teal">{mgukHorsepower}</span>
            <span className="text-xs font-mono text-[#5E686B] ml-1">BHP</span>
            <div className="w-full bg-gray-100 h-1.5 rounded-full mt-2 overflow-hidden">
              <div
                className="bg-accent-teal h-full transition-all duration-150"
                style={{ width: `${(mgukHorsepower / 163) * 100}%` }}
              />
            </div>
          </div>

          <div className="p-4 rounded-xl bg-white border border-[rgba(17,23,25,0.08)] shadow-sm">
            <span className="text-[10px] font-mono font-bold text-[#5E686B] uppercase block mb-1">
              TURBO BOOST
            </span>
            <span className="font-condensed font-black text-3xl text-[#151A1C]">{turboBoostBar}</span>
            <span className="text-xs font-mono text-[#5E686B] ml-1">BAR</span>
            <div className="w-full bg-gray-100 h-1.5 rounded-full mt-2 overflow-hidden">
              <div
                className="bg-orange-500 h-full transition-all duration-150"
                style={{ width: `${(Number(turboBoostBar) / 4.0) * 100}%` }}
              />
            </div>
          </div>

          <div className="p-4 rounded-xl bg-white border border-[rgba(17,23,25,0.08)] shadow-sm">
            <span className="text-[10px] font-mono font-bold text-[#5E686B] uppercase block mb-1">
              TOTAL SYSTEM POWER
            </span>
            <span className="font-condensed font-black text-3xl text-accent-teal">{totalPower}</span>
            <span className="text-xs font-mono text-[#5E686B] ml-1">HP</span>
            <div className="w-full bg-gray-100 h-1.5 rounded-full mt-2 overflow-hidden">
              <div
                className="bg-gradient-to-r from-accent-teal to-[#2BE7D6] h-full transition-all duration-150"
                style={{ width: `${(totalPower / 1063) * 100}%` }}
              />
            </div>
          </div>
        </div>
      </div>

      {/* Head-to-Head Drag & Circuit Simulator */}
      <div className="glass-panel rounded-2xl p-6 sm:p-8 border border-[rgba(17,23,25,0.12)] mb-16 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
          <div>
            <span className="text-[10px] font-mono font-bold tracking-widest text-accent-teal uppercase block">
              HEAD-TO-HEAD ACCELERATION RUN
            </span>
            <h3 className="font-condensed font-black text-2xl sm:text-3xl text-[#151A1C] uppercase">
              0 - 300 KM/H DRAG SPRINT
            </h3>
          </div>
          <button
            onClick={startRaceSimulation}
            disabled={isSimulatingRace}
            className={`px-6 py-2.5 rounded-xl font-mono text-xs font-bold tracking-widest uppercase transition-all duration-300 shadow-md ${
              isSimulatingRace
                ? 'bg-gray-400 text-white cursor-not-allowed'
                : 'bg-accent-teal hover:bg-accent-teal/90 text-white cursor-pointer shadow-teal-glow'
            }`}
          >
            {isSimulatingRace ? 'SIMULATING RUN...' : 'LAUNCH RACE SIMULATION'}
          </button>
        </div>

        {/* Race progress bars */}
        <div className="space-y-6">
          {/* W11 */}
          <div>
            <div className="flex justify-between text-xs font-mono mb-2">
              <span className="font-bold text-[#151A1C]">MERCEDES-AMG F1 W11 (2020)</span>
              <span className="text-accent-teal font-bold">{Math.round(raceProgress.w11)}% DISTANCE</span>
            </div>
            <div className="h-5 bg-gray-100 rounded-lg overflow-hidden border border-[rgba(17,23,25,0.08)] relative">
              <motion.div
                className="h-full bg-gradient-to-r from-[#151A1C] to-accent-teal rounded-lg flex items-center justify-end pr-2"
                style={{ width: `${raceProgress.w11}%` }}
              >
                <span className="text-[10px] font-mono font-bold text-white">W11</span>
              </motion.div>
            </div>
          </div>

          {/* W14 */}
          <div>
            <div className="flex justify-between text-xs font-mono mb-2">
              <span className="font-bold text-[#151A1C]">MERCEDES-AMG F1 W14 (2023)</span>
              <span className="text-accent-teal font-bold">{Math.round(raceProgress.w14)}% DISTANCE</span>
            </div>
            <div className="h-5 bg-gray-100 rounded-lg overflow-hidden border border-[rgba(17,23,25,0.08)] relative">
              <motion.div
                className="h-full bg-gradient-to-r from-[#151A1C] to-[#2BE7D6] rounded-lg flex items-center justify-end pr-2"
                style={{ width: `${raceProgress.w14}%` }}
              >
                <span className="text-[10px] font-mono font-bold text-white">W14</span>
              </motion.div>
            </div>
          </div>

          {/* AMG ONE */}
          <div>
            <div className="flex justify-between text-xs font-mono mb-2">
              <span className="font-bold text-[#151A1C]">MERCEDES-AMG ONE HYPERCAR (2023)</span>
              <span className="text-accent-teal font-bold">{Math.round(raceProgress.one)}% DISTANCE</span>
            </div>
            <div className="h-5 bg-gray-100 rounded-lg overflow-hidden border border-[rgba(17,23,25,0.08)] relative">
              <motion.div
                className="h-full bg-gradient-to-r from-gray-700 to-gray-500 rounded-lg flex items-center justify-end pr-2"
                style={{ width: `${raceProgress.one}%` }}
              >
                <span className="text-[10px] font-mono font-bold text-white">ONE</span>
              </motion.div>
            </div>
          </div>
        </div>
      </div>

      {/* Comprehensive Technical Comparison Matrix */}
      <div className="glass-panel rounded-2xl p-6 sm:p-8 border border-[rgba(17,23,25,0.12)] shadow-sm">
        <div className="mb-8">
          <span className="text-[10px] font-mono font-bold tracking-widest text-accent-teal uppercase block">
            TELEMETRY DATA MATRIX
          </span>
          <h3 className="font-condensed font-black text-2xl sm:text-3xl text-[#151A1C] uppercase">
            SIDE-BY-SIDE SPECIFICATIONS COMPARISON
          </h3>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b-2 border-[rgba(17,23,25,0.12)]">
                <th className="py-4 px-4 text-xs font-mono font-bold tracking-widest text-[#5E686B] uppercase">
                  METRIC BENCHMARK
                </th>
                <th className="py-4 px-4 text-xs font-mono font-bold tracking-widest text-[#151A1C] uppercase text-center bg-gray-50/50">
                  W14 (2023)
                </th>
                <th className="py-4 px-4 text-xs font-mono font-bold tracking-widest text-[#151A1C] uppercase text-center">
                  W11 (2020)
                </th>
                <th className="py-4 px-4 text-xs font-mono font-bold tracking-widest text-[#151A1C] uppercase text-center bg-gray-50/50">
                  AMG ONE (2023)
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[rgba(17,23,25,0.06)]">
              {COMPARISON_METRICS.map((metric, idx) => (
                <tr key={idx} className="hover:bg-white/60 transition-colors">
                  <td className="py-4 px-4">
                    <span className="font-bold text-sm text-[#151A1C] block">{metric.label}</span>
                    <span className="text-[11px] text-[#5E686B] mt-0.5 block">{metric.description}</span>
                  </td>
                  <td className="py-4 px-4 text-center font-mono font-bold text-sm text-[#151A1C] bg-gray-50/50">
                    {metric.w14} <span className="text-[10px] text-[#5E686B]">{metric.unit}</span>
                  </td>
                  <td className="py-4 px-4 text-center font-mono font-bold text-sm text-[#151A1C]">
                    {metric.w11} <span className="text-[10px] text-[#5E686B]">{metric.unit}</span>
                  </td>
                  <td className="py-4 px-4 text-center font-mono font-bold text-sm text-[#151A1C] bg-gray-50/50">
                    {metric.one} <span className="text-[10px] text-[#5E686B]">{metric.unit}</span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
